max_width = 100
edition = "2021"
use_small_heuristics = "Max"
newline_style = "Unix"
tab_spaces = 4
hard_tabs = false
reorder_imports = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
wrap_comments = true 