[package]
name = "common-rpc"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../../common" }
solana-sdk = "1.18.26"
solana-client = "1.18.26"
solana-account-decoder = "1.18.26"
thiserror = "2.0.11" 
lazy_static = "1.4.0" 