[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
thiserror = "2.0.11"
chrono = { version = "0.4.40", features = ["serde"] }